language: php
php:
  - 5.4
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/bin

env:
  global:
    - MAGENTO_DB_NAME=magento
    - MAGENTO_URL=mercadopago.local
    - DB=mysql
  matrix:
   - BEHAT_TAG=@CardED

addons:
  hosts:
    - mercadopago.local

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
  - sh -c 'if [ "$CASHER_DIR" ]; then
         if [ -x $HOME/.cache/bin/composer ]; then
           $HOME/.cache/bin/composer self-update; echo '';
         else
           mkdir -p $HOME/.cache/bin;
           curl --connect-timeout 30 -sS https://getcomposer.org/installer
           | php -- --install-dir $HOME/.cache/bin/ --filename composer;
         fi
       fi'
  - export PATH="$HOME/.cache/bin:$PATH"
  - composer self-update

install:
  - sudo apt-get install apache2 libapache2-mod-fastcgi

before_script:
  - sudo service postfix stop
    - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
    - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
    - >
        echo 'sendmail_path = "/usr/sbin/sendmail -t -i "'
        | sudo tee "/home/travis/.phpenv/versions/`php -i
        | grep "PHP Version"
        | head -n 1
        | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"

  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f .travis/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - cp -f .travis/composer.json composer.json
  - composer install --no-interaction
  - mkdir tmp
  - curl -o ./tmp/sample-data.tgz https://raw.githubusercontent.com/Vinai/compressed-magento-sample-data/1.9.1.0/compressed-no-mp3-magento-sample-data-1.9.1.0.tgz
  - tar -xzf ./tmp/sample-data.tgz -C ./tmp/
  - mysql -e "DROP DATABASE IF EXISTS ${MAGENTO_DB_NAME}; CREATE DATABASE ${MAGENTO_DB_NAME};"
  - mysql magento < ./tmp/magento-sample-data-1.9.1.0/magento_sample_data_for_1.9.1.0.sql
  - cp -R ./tmp/magento-sample-data-1.9.1.0/media/ ./htdocs/media/
  - cp -R ./tmp/magento-sample-data-1.9.1.0/skin/ ./htdocs/skin/
  - php ./htdocs/install.php --license_agreement_accepted 'yes' --locale 'en_US' --db_host '127.0.0.1' --db_name ${MAGENTO_DB_NAME} --db_user 'travis' --timezone 'America/Los_Angeles' --default_currency 'USD' --skip_url_validation 'yes' --url "http://${MAGENTO_URL}/" --secure_base_url "http://${MAGENTO_URL}/" --use_rewrites 'yes' --use_secure 'no' --use_secure_admin 'no' --session_save 'db' --admin_firstname 'Facundo' --admin_lastname 'Capua' --admin_email 'fcapua@summasolutions.net' --admin_username 'admin' --admin_password 'MercadoPago2015'
  - cp -R v1.6.x\ -\ 1.9.x\ -\ Transparent/* htdocs/
  - ls -al htdocs/app/code/community/
  - ls -al bin/
  - bin/phing -f .travis/build/build.xml magento_configuration
  - rm -rf htdocs/var/cache
  - cd v1.6.x\ -\ 1.9.x\ -\ Transparent/dev/MercadoPago/tests/
  - cp behat.yml.dist behat.yml
  - sed -e "s?%MAGENTO_URL%?http://${MAGENTO_URL}/?g" --in-place behat.yml
  - sed -e "s?%BROWSER_DRIVER%?firefox?g" --in-place behat.yml
  - composer install --no-interaction
  - "phantomjs --webdriver=4444 > /dev/null &"
  - sleep 5


script:
  - vendor/bin/phpmd ../../../app/code/community/MercadoPago text static/phpmd/ruleset.xml
  - vendor/bin/phpcs --standard=static/phpcs/Ecg --colors ../../../app/
  - vendor/bin/phpcpd ../../../ --exclude=dev
  - vendor/bin/behat --config behat.yml --tags ${BEHAT_TAG} --tags="~@skip" 
